In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# to lowercase

In [5]:
df['review']=df['review'].str.lower()

# remove html tags

In [6]:
import re
def removehtmltags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [7]:
text='<h1>Main Title</h1> <h2>Sub-topic Title</h2> <h3>Section Title</h3>'

In [8]:
removehtmltags(text)

'Main Title Sub-topic Title Section Title'

In [9]:
df['review']=df['review'].apply(removehtmltags)

In [10]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# remove links  and urls

In [11]:
def removeurl(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [12]:
text1='this is my website https://www.ahmadnawaz.com/ucp/notebook15sdfd5'
text2='google search here www.google.com'

In [13]:
removeurl(text2)

'google search here '

# remove punctuation marks

In [14]:
import string,time

In [15]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
ex=string.punctuation

In [17]:
def removepun(text):
    for char in ex:
        text=text.replace(char,'')
    return text

In [18]:
text='ahsdjkes * ? ! $ali ahmad'

In [19]:
removepun(text)

'ahsdjkes    ali ahmad'

In [20]:
start=time.time()
print(removepun(text))
tim1=time.time()-start
print(tim1)

ahsdjkes    ali ahmad
0.0004153251647949219

In [21]:
def removep(text):
    return text.translate(str.maketrans('','',ex))

In [22]:
start=time.time()
print(removep(text))
tim2=time.time()-start
print(tim2)

ahsdjkes    ali ahmad
0.0005924701690673828

In [23]:
tim1/tim2

0.7010060362173038

In [24]:
tw = pd.read_csv("train.csv",)

In [25]:
tw.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [26]:
tw['tweet']=tw['tweet'].apply(removep)

In [27]:
tw.head()

   id  label                                              tweet
0   1      0   user when a father is dysfunctional and is so...
1   2      0  user user thanks for lyft credit i cant use ca...
2   3      0                                bihday your majesty
3   4      0  model   i love u take with u all the time in u...
4   5      0               factsguide society now    motivation

# chat word treatment

In [28]:
slang_dict = {}

with open('slang.txt', 'r') as file:
    for line in file:
        if line.strip():
            key, value = line.split('=', 1)
            slang_dict[key.strip()] = value.strip()

print(slang_dict)

{'A3': 'Anytime, Anywhere, Anyplace', 'ADIH': 'Another Day In Hell', 'AFK': 'Away From Keyboard', 'AFAIK': 'As Far As I Know', 'ASAP': 'As Soon As Possible', 'ASL': 'Age, Sex, Location', 'ATK': 'At The Keyboard', 'ATM': 'At The Moment', 'BAE': 'Before Anyone Else', 'BAK': 'Back At Keyboard', 'BBL': 'Be Back Later', 'BBS': 'Be Back Soon', 'BFN': 'Bye For Now', 'B4N': 'Bye For Now', 'BRB': 'Be Right Back', 'BRUH': 'Bro', 'BRT': 'Be Right There', 'BSAAW': 'Big Smile And A Wink', 'BTW': 'By The Way', 'BWL': 'Bursting With Laughter', 'CSL': 'Canâ€™t Stop Laughing', 'CU': 'See You', 'CUL8R': 'See You Later', 'CYA': 'See You', 'DM': 'Direct Message', 'FAQ': 'Frequently Asked Questions', 'FC': 'Fingers Crossed', 'FIMH': 'Forever In My Heart', 'FOMO': 'Fear Of Missing Out', 'FR': 'For Real', 'FWIW': "For What It's Worth", 'FYP': 'For You Page', 'FYI': 'For Your Information', 'G9': 'Genius', 'GAL': 'Get A Life', 'GG': 'Good Game', 'GMTA': 'Great Minds Think Alike', 'GN': 'Good Night', 'GOAT': 'Greatest Of All Time', 'GR8': 'Great!', 'HBD': 'Happy Birthday', 'IC': 'I See', 'ICQ': 'I Seek You', 'IDC': 'I Donâ€™t Care', 'IDK': "I Don't Know", 'IFYP': 'I Feel Your Pain', 'ILU': 'I Love You', 'ILY': 'I Love You', 'IMHO': 'In My Honest/Humble Opinion', 'IMU': 'I Miss You', 'IMO': 'In My Opinion', 'IOW': 'In Other Words', 'IRL': 'In Real Life', 'IYKYK': 'If You Know, You Know', 'JK': 'Just Kidding', 'KISS': 'Keep It Simple, Stupid', 'L': 'Loss', 'L8R': 'Later', 'LDR': 'Long Distance Relationship', 'LMK': 'Let Me Know', 'LMAO': 'Laughing My A** Off', 'LOL': 'Laughing Out Loud', 'LTNS': 'Long Time No See', 'M8': 'Mate', 'MFW': 'My Face When', 'MID': 'Mediocre', 'MRW': 'My Reaction When', 'MTE': 'My Thoughts Exactly', 'NVM': 'Never Mind', 'NRN': 'No Reply Necessary', 'NPC': 'Non-Player Character', 'OIC': 'Oh I See', 'OP': 'Overpowered', 'PITA': 'Pain In The A**', 'POV': 'Point Of View', 'PRT': 'Party', 'PRW': 'Parents Are Watching', 'ROFL': 'Rolling On The Floor Laughing', 'ROFLOL': 'Rolling On The Floor Laughing Out Loud', 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off', 'RN': 'Right Now', 'SK8': 'Skate', 'STATS': 'Your Sex And Age', 'SUS': 'Suspicious', 'TBH': 'To Be Honest', 'TFW': 'That Feeling When', 'THX': 'Thank You', 'TIME': 'Tears In My Eyes', 'TLDR': 'Too Long, Didnâ€™t Read', 'TNTL': 'Trying Not To Laugh', 'TTFN': 'Ta-Ta For Now!', 'TTYL': 'Talk To You Later', 'U': 'You', 'U2': 'You Too', 'U4E': 'Yours For Ever', 'W': 'Win', 'W8': 'Wait...', 'WB': 'Welcome Back', 'WTF': 'What The F**k', 'WTG': 'Way To Go!', 'WUF': 'Where Are You From?', 'WYD': 'What You Doing?', 'WYWH': 'Wish You Were Here', 'ZZZ': 'Sleeping, Bored, Tired'}

In [29]:
def chatconversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in slang_dict:
            new_text.append(slang_dict[w.upper()])
        else:
            new_text.append(w)
    return ' '.join(new_text)

In [30]:
chatconversion('lmao i am good')

'Laughing My A** Off i am good'

# spelling correction

In [31]:
from textblob import TextBlob

In [32]:
incorr= 'ccertrain condtioons durng sevarl ggeneration arce modifed in the same mannner'

In [33]:
textb=TextBlob(incorr)
textb.correct().string

'certain conditions during several generation are modified in the same manner'

# remove stop words

In [34]:
from nltk.corpus import stopwords

In [35]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [36]:
from nltk.corpus import stopwords

def revestop(text):
    newtxt = []
    stop_words = set(stopwords.words('english'))
    
    for word in text.split():
        if word.lower() not in stop_words: 
            newtxt.append(word)
            
    return ' '.join(newtxt)

In [37]:
revestop('i am yours brother')

'brother'

# handling emoji

In [38]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [39]:
remove_emoji('😀 this is very funny ha😞😲😲')

' this is very funny ha'

In [40]:
import emoji

In [41]:
print(emoji.demojize('😀 this is very funny ha😞😲😲'))

:grinning_face: this is very funny ha:disappointed_face::astonished_face::astonished_face:

# tokenization

## using the split fun

In [42]:
sen='hi this is ahmad nawaz'
sen.split()

['hi', 'this', 'is', 'ahmad', 'nawaz']

In [43]:
sen='hi this is ahmad nawaz. and i am learning nlp. through campux x'
sen.split('.')

['hi this is ahmad nawaz', ' and i am learning nlp', ' through campux x']

In [44]:
sent=' i am from lhr!'
sent.split()

['i', 'am', 'from', 'lhr!']

### through regular expression

In [45]:
import re

sent3 = 'I am going to delhi!'
tokens = re.findall("[\w]+", sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [46]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

## NLTK

In [47]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [49]:
sen1='i am going to visit lahore!'
word_tokenize(sen1)

['i', 'am', 'going', 'to', 'visit', 'lahore', '!']

In [50]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

# Spacy

In [55]:
import spacy
nlp=spacy.load('en_core_web_sm')

!python -m spacy download en_core_web_sm

In [56]:
doc1=nlp(text)

In [57]:
for token in doc1:
    print(token)

Lorem
Ipsum
is
simply
dummy
text
of
the
printing
and
typesetting
industry
?


Lorem
Ipsum
has
been
the
industry
's
standard
dummy
text
ever
since
the
1500s
,


when
an
unknown
printer
took
a
galley
of
type
and
scrambled
it
to
make
a
type
specimen
book
.

## Stemming

### for english porterstemmer and for other lang snowball stemmer

In [58]:
from nltk.stem.porter import PorterStemmer

In [59]:
ps= PorterStemmer()

In [62]:
def stem_words(text):
    return ' '.join([ps.stem(word) for word in text.split()])

In [63]:
sample="walked like you are loving it"
stem_words(sample)

'walk like you are love it'

In [64]:
sample='walked walks walking walkeed'
stem_words(sample)

'walk walk walk walke'

# Lemmatization

In [69]:
import nltk

nltk.download('wordnet')

nltk.download('omw-1.4')

nltk.download('punkt')
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word", "Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

[nltk_data] Downloading package wordnet to C:\Users\Ahmad
[nltk_data]     Nawaz\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Ahmad
[nltk_data]     Nawaz\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Ahmad
[nltk_data]     Nawaz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!